fastlane_version "2.56.0"

default_platform :mac
xcversion(version: '9.0')

platform :mac do
  before_all do
    cocoapods
  end

  desc 'Install input method to local'
  lane :try do
    system 'rm -rf ../Build/EmojiIM.app'
    gym

    input_methods = Pathname.new('/Library/Input Methods/EmojiIM.app')
    target = input_methods.join('EmojiIM.app')
    system <<-SHELL
    sudo rm -rf '#{target}'
    sudo cp -r ../Build/EmojiIM.app '#{input_methods}'
    sudo pluginkit -v -a '#{target.join('Contents', 'PlugIns', 'EmojiIM_Extension.appex')}'
    sudo killall -9 EmojiIM_Extension
    SHELL
  end

  desc 'Runs all the tests'
  lane :test do
    swiftlint(executable: './Pods/SwiftLint/swiftlint')
    scan
  end
end
